### ISSUE TITLE
Change annotations when changing language

### ISSUE THREAD

**Issue by garciadelcastillo** [v-xup6/MultilingualGH#4]
When component is dropped, it generates annotations for whichever default language. But if language is changed, annotations stay in the previous form. It would be nice to refresh all doc annotations when switching between languages :)

**Comment by lin-ycv** [comment]
Which version are you on?
Annotation generation on component drop has been turned off in v0.6.0, since I rather the user explicitly select a language before I waste computational resource annotating.
Also I believe I've added an option (renew on new language) to the right click menu since v0.5.0.
By default it's not on, since I assume language selection mostly happens when a new MGH is created. It also takes time to clear all the previous annotations and reannotate, especially if the file is large with many components, so I rather the user be explicit about clearing annotations.

But I think I see where you're coming from, if this is an educational tool and we're changing languages mid file for explaining to different people, it's more convenient if it changes automatically. 

Which default behavior do you think is more desirable?

**Comment by garciadelcastillo** [comment]
Oh, I see your concern about resources. 

I think my angle would be: this is probably designed for beginners trying to learn the platform. So, I would favor user experience vs. resources. I find it strange to switch language and not have things update (makes me think I did something wrong). And, if you think of it from the opposite direction: how likely is it that someone actively changes languages, but wishes components to remain in the previously chosen one? I can't think of a good use case for that. 

Even if GH takes a few seconds to update the display, I don't think that's a big deal :)

**Comment by lin-ycv** [comment]
Fair point.
New release with this change (and new feature, some minor bug fixes, tweaks..etc)
https://github.com/v-xup6/MultilingualGH/releases/tag/0.7.0
